### ISSUE TITLE
Aplay error after upgrade to home assistant 2023.6.1

### ISSUE THREAD

**Issue by VenominousX** [rhasspy/rhasspy-voltron#336]
Hi,

after upgrading to ha 2023.6.1 I have some problems with the text output. The hotword is recognized and some actions are triggered by the hotword recognition, also the intents work as expected. Only the wav output does not work anymore. My master satellite setup communicates via mqtt.

[DEBUG:2023-06-10 11:41:04,218] rhasspywake_porcupine_hermes: Receiving audio wohnzimmer.wzsite1
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM 0
aplay: main:828: audio open error: No such file or directory
[ERROR:2023-06-10 11:41:04,234] rhasspyspeakers_cli_hermes: handle_play
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-speakers-cli-hermes/rhasspyspeakers_cli_hermes/__init__.py", line 88, in handle_play
    subprocess.run(self.play_command, input=wav_bytes, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['aplay', '-q', '-t', 'wav', '-D', '0']' returned non-zero exit status 1.

**Comment by OlliePugh** [comment]
I see you closed this as completed? What was the solution?
